services:
  # 开发服务 - 用于VS Code开发环境
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - TERM=xterm-256color
      - COLORTERM=truecolor
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    command: /bin/bash
    tty: true
    stdin_open: true
    ports:
      - "8000:8000"

  # 基础服务 - 用于运行LLM API等基础功能
  base:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    working_dir: /app
    command: python -m tools.llm_api --prompt "Hello, this is a test message"

  # 爬虫服务 - 包含浏览器依赖
  scraper:
    build: 
      context: .
      dockerfile: Dockerfile.scraper
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null
    tty: true
